---
approval_rules:
  - description: A rule that requires status checks to be green
    if:
      has_successful_status:
        - "Commit linting"
        - "node linting"
    name: status checks
    options:
      allow_author: false
      allow_contributor: false
      invalidate_on_push: true

  - description: A rule that dont require approvals if signed by pre-approved signing-keys
    if:
      has_author_in:
        teams:
          - "Sea-Shell/seashell"
      has_valid_signatures: true
      has_valid_signatures_by:
        teams:
          - "Sea-Shell/seashell"
    name: pre-approved signatures
    options:
      request_review:
        enabled: false
    requires:
      count: 0

  - description: Rule to approve PR when label is patch, author is dependabot
    if:
      author_is_only_contributor: true
      has_author_in:
        users:
          - "dependabot[bot]"
      has_labels:
        - "dependencies"
        - "patch"
      has_valid_signatures: true
      has_valid_signatures_by_keys:
        key_ids:
          - B5690EEEBB952194
    name: dependabot-patch
    options:
      request_review:
        enabled: false
    requires:
      count: 0

  - description: Rule to approve PR when label is minor, author is dependabot
    if:
      author_is_only_contributor: true
      has_author_in:
        users:
          - "dependabot[bot]"
      has_labels:
        - "dependencies"
        - "minor"
      has_valid_signatures: true
      has_valid_signatures_by_keys:
        key_ids:
          - B5690EEEBB952194
    name: dependabot-minor
    options:
      request_review:
        enabled: false
    requires:
      count: 0

  - description: review when needed
    name: reviews
    options:
      request_review:
        enabled: true
        mode: teams
    requires:
      count: 1
      permissions:
        - "write"
      teams:
        - "Sea-Shell/seashell"

policy:
  approval:
    - and:
      - status checks
      - or:
          - pre-approved signatures
          - dependabot-patch
          - dependabot-minor
          - reviews
  disapproval:
    requires:
      teams:
        - "Sea-Shell/seashell"
